//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentsPanelExtension.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgentsPanelExtension.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refresh now.
        /// </summary>
        public static string Action_Refresh {
            get {
                return ResourceManager.GetString("Action_Refresh", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Action_Settings {
            get {
                return ResourceManager.GetString("Action_Settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Action_Open {
            get {
                return ResourceManager.GetString("Action_Open", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The legal bit.
        /// </summary>
        public static string Page_Legal_Title {
            get {
                return ResourceManager.GetString("Page_Legal_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} is a background extension.
        ///
        ///To use it, open PowerToys Command Palette and search for &quot;{1}&quot;.
        /// </summary>
        public static string DirectLaunch_Message {
            get {
                return ResourceManager.GetString("DirectLaunch_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to # The Legal Bit
        ///
        ///This app is an **independent, third-party tool**. It is **not
        ///affiliated with, endorsed by, or connected to** Anthropic, Claude,
        ///OpenAI, ChatGPT, GitHub, Copilot, or any AI provider. Provider names
        ///and logos belong to their respective owners. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Legal_Markdown {
            get {
                return ResourceManager.GetString("Legal_Markdown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The saved {0} sign-in has expired.
        /// </summary>
        public static string Dock_Expired_Subtitle {
            get {
                return ResourceManager.GetString("Dock_Expired_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rate-limited.
        /// </summary>
        public static string Dock_RateLimited_Title {
            get {
                return ResourceManager.GetString("Dock_RateLimited_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Token expired.
        /// </summary>
        public static string Dock_Expired_Title {
            get {
                return ResourceManager.GetString("Dock_Expired_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} login not found.
        /// </summary>
        public static string Dock_SignIn_Subtitle {
            get {
                return ResourceManager.GetString("Dock_SignIn_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not signed in.
        /// </summary>
        public static string Dock_SignIn_Title {
            get {
                return ResourceManager.GetString("Dock_SignIn_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} used.
        /// </summary>
        public static string Extra_UsedOfLimit {
            get {
                return ResourceManager.GetString("Extra_UsedOfLimit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} used.
        /// </summary>
        public static string Extra_Used {
            get {
                return ResourceManager.GetString("Extra_Used", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Plan — {0}.
        /// </summary>
        public static string Plan_Title {
            get {
                return ResourceManager.GetString("Plan_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to resets {0}.
        /// </summary>
        public static string Reset_At {
            get {
                return ResourceManager.GetString("Reset_At", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to stale — as of {0}.
        /// </summary>
        public static string Stale_AsOf {
            get {
                return ResourceManager.GetString("Stale_AsOf", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Can't reach {0}.
        /// </summary>
        public static string Status_Error_Title {
            get {
                return ResourceManager.GetString("Status_Error_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Showing the last known numbers — check your connection.
        /// </summary>
        public static string Status_Error_Subtitle {
            get {
                return ResourceManager.GetString("Status_Error_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Status_Error_Tag {
            get {
                return ResourceManager.GetString("Status_Error_Tag", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not signed in to {0}.
        /// </summary>
        public static string Status_NotSignedIn_Title {
            get {
                return ResourceManager.GetString("Status_NotSignedIn_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No sign-in found on this PC.
        /// </summary>
        public static string Status_NotSignedIn_Subtitle {
            get {
                return ResourceManager.GetString("Status_NotSignedIn_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not signed in.
        /// </summary>
        public static string Status_NotSignedIn_Tag {
            get {
                return ResourceManager.GetString("Status_NotSignedIn_Tag", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} is rate-limiting usage checks.
        /// </summary>
        public static string Status_RateLimited_Title {
            get {
                return ResourceManager.GetString("Status_RateLimited_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Showing the last known numbers — will retry automatically.
        /// </summary>
        public static string Status_RateLimited_Subtitle {
            get {
                return ResourceManager.GetString("Status_RateLimited_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rate-limited.
        /// </summary>
        public static string Status_RateLimited_Tag {
            get {
                return ResourceManager.GetString("Status_RateLimited_Tag", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} sign-in expired.
        /// </summary>
        public static string Status_TokenExpired_Title {
            get {
                return ResourceManager.GetString("Status_TokenExpired_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The saved sign-in has expired.
        /// </summary>
        public static string Status_TokenExpired_Subtitle {
            get {
                return ResourceManager.GetString("Status_TokenExpired_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string Status_TokenExpired_Tag {
            get {
                return ResourceManager.GetString("Status_TokenExpired_Tag", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No usage data.
        /// </summary>
        public static string Usage_Empty_Title {
            get {
                return ResourceManager.GetString("Usage_Empty_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The account reported no active limits.
        /// </summary>
        public static string Usage_Empty_Subtitle {
            get {
                return ResourceManager.GetString("Usage_Empty_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Extra usage.
        /// </summary>
        public static string Window_Extra_Long {
            get {
                return ResourceManager.GetString("Window_Extra_Long", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Extra.
        /// </summary>
        public static string Window_Extra_Short {
            get {
                return ResourceManager.GetString("Window_Extra_Short", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Weekly — {0}.
        /// </summary>
        public static string Window_ModelWeek_Long {
            get {
                return ResourceManager.GetString("Window_ModelWeek_Long", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Monthly — {0}.
        /// </summary>
        public static string Window_MonthQualified_Long {
            get {
                return ResourceManager.GetString("Window_MonthQualified_Long", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Monthly (30-day).
        /// </summary>
        public static string Window_Month_Long {
            get {
                return ResourceManager.GetString("Window_Month_Long", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mo.
        /// </summary>
        public static string Window_Month_Short {
            get {
                return ResourceManager.GetString("Window_Month_Short", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Session (5-hour).
        /// </summary>
        public static string Window_Session_Long {
            get {
                return ResourceManager.GetString("Window_Session_Long", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 5h.
        /// </summary>
        public static string Window_Session_Short {
            get {
                return ResourceManager.GetString("Window_Session_Short", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Weekly (all models).
        /// </summary>
        public static string Window_Week_Long {
            get {
                return ResourceManager.GetString("Window_Week_Long", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Wk.
        /// </summary>
        public static string Window_Week_Short {
            get {
                return ResourceManager.GetString("Window_Week_Short", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Agents Panel.
        /// </summary>
        public static string Command_AgentsPanel {
            get {
                return ResourceManager.GetString("Command_AgentsPanel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Agents Panel for Command Palette.
        /// </summary>
        public static string Extension_DisplayName {
            get {
                return ResourceManager.GetString("Extension_DisplayName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Agents Panel.
        /// </summary>
        public static string Page_Usage_Title {
            get {
                return ResourceManager.GetString("Page_Usage_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Usage refresh interval in minutes (minimum 3; 0 turns auto-refresh off).
        /// </summary>
        public static string Settings_Refresh_Desc {
            get {
                return ResourceManager.GetString("Settings_Refresh_Desc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refresh interval.
        /// </summary>
        public static string Settings_Refresh_Label {
            get {
                return ResourceManager.GetString("Settings_Refresh_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show pay-as-you-go extra usage when the account reports it.
        /// </summary>
        public static string Settings_ShowExtraUsage_Desc {
            get {
                return ResourceManager.GetString("Settings_ShowExtraUsage_Desc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Extra usage.
        /// </summary>
        public static string Settings_ShowExtraUsage_Label {
            get {
                return ResourceManager.GetString("Settings_ShowExtraUsage_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show model-specific limits (e.g. Opus, Sonnet) as their own rows.
        /// </summary>
        public static string Settings_ShowModelWindows_Desc {
            get {
                return ResourceManager.GetString("Settings_ShowModelWindows_Desc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Per-model weekly limits.
        /// </summary>
        public static string Settings_ShowModelWindows_Label {
            get {
                return ResourceManager.GetString("Settings_ShowModelWindows_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GitHub token for Copilot usage (optional — blank uses your gh CLI / Copilot sign-in).
        /// </summary>
        public static string Settings_CopilotToken_Desc {
            get {
                return ResourceManager.GetString("Settings_CopilotToken_Desc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copilot GitHub token.
        /// </summary>
        public static string Settings_CopilotToken_Label {
            get {
                return ResourceManager.GetString("Settings_CopilotToken_Label", resourceCulture);
            }
        }
    }
}
